apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  annotations:
    meta.helm.sh/release-name: gloo
    meta.helm.sh/release-namespace: gloo-system
  creationTimestamp: "2021-10-25T19:24:29Z"
  generation: 2
  labels:
    discovered_by: kubernetesplugin
  name: gloo-system-gloo-9976
  namespace: gloo-system
  resourceVersion: "837"
  selfLink: /apis/gloo.solo.io/v1/namespaces/gloo-system/upstreams/gloo-system-gloo-9976
  uid: 4091a135-6a0f-49d3-9774-56c53f1fb540
spec:
  discoveryMetadata:
    labels:
      app: gloo
      app.kubernetes.io/managed-by: Helm
      gloo: gloo
  kube:
    selector:
      gloo: gloo
    serviceName: gloo
    serviceNamespace: gloo-system
    servicePort: 9976
status:
  statuses:
    gloo-system:
      reportedBy: gloo
      state: 1
